# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: photo_uploader_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: photo_uploader_web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      # Adicione o volume de storage para persistir os arquivos
      - storage_data:/rails/storage
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
  storage_data: