# config/recurring.yml
production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  # --- TAREFA ADICIONADA AQUI ---
  reprocess_failed_videos:
    command: "videos:reprocess_failed"
    schedule: every 5 minutes